Repository Taro-IT/docs, pull requests merged in 2021-11, with the labels that each got.

#145 feat: add ch07 to p04
  docs/checklists/CH07-checklist-presentaciones.md
  docs/procesos/P04-proceso-de-presentaciones.md
Labels: checklist

#144 Feat/update cmmi tab
  docs/plantillas/PL02-plantilla-para-guias.md
  docs/plantillas/PL03-plantilla-para-procesos.md
  docs/tablero-cmmi.md
  static/img/tablero-cmmi/segunda-entrega-scampi-2.png
  static/img/tablero-cmmi/segunda-entrega-scampi.png
Labels: enhancement

#150 docs: se agrego G22 - Guia para estimar un work item
  docs/guias/G22-guia-para-estimar-workitem.md
Labels: documentation, guías

#148 Docs/g23 guia trials temple
  docs/guias/G23-guia-trials-temple.md
Labels: documentation, guías

#152 docs: hacer referencia al plan de recursos y el WBS en el P15
  docs/procesos/P15-proceso-planeacion-de-iteracion.md
Labels: documentation

#166 Docs/pol05 compromiso stakeholders
  docs/politicas/POL05-compromiso-stakeholders.md
Labels: documentation, políticas

#164 docs: añadir matriz de retrospectives
  docs/procesos/P20-proceso-retrospective.md
Labels: documentation

#163 add P06 Proceso obtención y análisis de métricas
  docs/procesos/P06-proceso-obtencion-metricas.md
Labels: documentation

#174 fix/change input and output of P20 and P28
  docs/procesos/P20-proceso-retrospective.md
  docs/procesos/P28-proceso-atender-retro.md
Labels: documentation

#143 Feat/p30 proceso toma decisiones
  docs/procesos/P02-proceso-juntas-socios-formadores.md
  docs/procesos/P30-proceso-toma-de-decisiones.md
  package-lock.json
Labels: documentation

#149 docs: medidas de prevencion a POL03
  docs/checklists/CH08-entrega-de-SCAMPI.md
  docs/codigo-etica.md
  docs/politicas/POL03-politica-manejo-datos.md
  docs/procesos/P09-proceso-entrega-de-scampi.md
Labels: documentation

#186 docs: modificar G15 para realizar un plan de comunicación
  docs/guias/G15-guia-ubicar-interesados-en-la-matriz-de-interesados.md
  docs/plantillas/PL16-plantilla-para-plan-comunicacion.md
  docs/procesos/P11-proceso-de-definicion-del-plan-inicial.md
  static/img/guias/G15/matrizEjemplo.png
  static/img/guias/G15/matrizInteresados.png
Labels: documentation

#194 Feat/modifications for ver and val
  docs/guias/G18-guia-pull-request.md
  docs/procesos/P02-proceso-juntas-socios-formadores.md
  docs/procesos/P03-proceso-institucionalizacion-assets.md
  docs/procesos/P09-proceso-entrega-de-scampi.md
  docs/procesos/P14-proceso-reporte-estado.md
  docs/procesos/P15-proceso-de-auditorias.md
  docs/procesos/P17-proceso-trabajo-parejas.md
  docs/procesos/P21-proceso-verificacion-items.md
  docs/procesos/P22-proceso-analisis-metricas.md
  static/img/guias/G18/ci-fail.png
  static/img/guias/G18/ci-success.png
Labels: documentation

#185 Docs/pol06 gestion conocimiento
  docs/politicas/POL06-gestion-conocimiento.md
  docs/procesos/P12-proceso-planeacion-de-iteracion.md
  docs/procesos/P16-proceso-retrospective.md
Labels: documentation

#167 Fix/p11 refactor
  docs/guias/G19-guia-para-estimar-workitem.md
  docs/plantillas/PL07-plantilla-para-planeacion-personal.md
  docs/plantillas/PL07-plantilla-para-vision-statement-de-un-plan.md
  docs/plantillas/PL08-plantilla-para-documentacion-de-un-plan.md
  docs/plantillas/PL08-plantilla-para-plan-departamental.md
  docs/plantillas/PL09-plantilla-para-planeacion-de-iteracion.md
  docs/plantillas/Pl17-plantilla-inventario-habilidades.md
  docs/procesos/P11-proceso-de-definicion-del-plan-inicial.md
Labels: documentation

#203 docs: guia para competencias
  docs/guias/G26-guia-para-evaluaciones-individuales.md
Labels: documentation

#202 docs: agradecimientos
  docs/intro.md
Labels: documentation

#207 G27 Guía de release de la wiki
  docs/guias/G27-Guía-de-release-de-la-wiki.md
  docs/politicas/POL07-validacion.md
  docs/procesos/P23-proceso-release-linea-base.md
  docs/procesos/P25-proceso-validacion-socios.md
  static/img/guias/G27/g27-img-1.png
  static/img/guias/G27/g27-img-2.png
  static/img/guias/G27/g27-img-3.png
  static/img/guias/G27/g27-img-4.png
  static/img/guias/G27/g27-img-5.png
  static/img/guias/G27/g27-img-6.png
  static/img/guias/G27/g27-img-7.png
Labels: guías
